server:
  port: 81
spring:
  application:
    name: springcloud-consumer-feign
  #rabbitmq服务
  rabbitmq:
    username: Allen
    password: lwxa1421
    virtual-host: /allen
    host: 114.115.180.17
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: springcloud-consumer:${server.port}
    #设置客户端访问超时 模拟远程调用触发熔断机制时需要配置
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

  #客户端开启降级
feign:
  hystrix:
    enabled: true
